-- Enable Row Level Security (RLS) is recommended for all tables
-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  avatar_url text,
  constraint username_length check (char_length(full_name) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for categories
create table categories (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table categories enable row level security;

create policy "Users can view their own categories." on categories
  for select using (auth.uid() = user_id);

create policy "Users can insert their own categories." on categories
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own categories." on categories
  for update using (auth.uid() = user_id);

create policy "Users can delete their own categories." on categories
  for delete using (auth.uid() = user_id);

-- Create a table for wishlist items
create table items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  category_id bigint references categories,
  name text not null,
  price numeric,
  description text,
  image_url text,
  buy_link text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table items enable row level security;

create policy "Users can view their own items." on items
  for select using (auth.uid() = user_id);

create policy "Users can insert their own items." on items
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own items." on items
  for update using (auth.uid() = user_id);

create policy "Users can delete their own items." on items
  for delete using (auth.uid() = user_id);

-- Set up Storage for Images (Optional but recommended)
-- You'll need to create a bucket named 'avatars' and 'items' in the Supabase Dashboard Storage section.

-- AUTOMATIC PROFILE CREATION TRIGGER
-- This ensures a profile is created every time a new user signs up via Auth.
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    'https://ui-avatars.com/api/?name=' || (new.raw_user_meta_data->>'full_name') || '&background=random'
  );
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
